name: Add to Release Assets
on:
  release:
     types: [published]
  push:
     tags:
     - '*'
  workflow_dispatch:

jobs:
  upload-to-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get artifacts from previous workflow
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: mulle-linux-package.yml
          workflow_conclusion: success
          name: Linux-packages
          path: ./release-files

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./release-files/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
